### ISSUE TITLE
SSID containing a space " ".

### ISSUE THREAD

**Issue by j0nnymofo** [jblanked/FlipWeather#3]
Hi jblanked. Just got a flipper and see you have been hard at work!! well done.

I have an SSID that contains spaces. Here is the exact one: "Pretty Fly For A WiFi". Is it possible to add the option for a space in the SSID text input please?
![Screenshot-20241226-233325](https://github.com/user-attachments/assets/a771715d-ec3e-4c24-a36f-b6af85298bb0)

**Comment by jblanked** [comment]
Hey, thanks for checking out my work 🔥 hold the underscore key for a space

**Comment by j0nnymofo** [comment]
That's excellent man. Thanks for the fast reply! Confirmed working for me now. Thanks very much. Keep up the great work.
